services:
  airbyte-db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: airbyte
      POSTGRES_DB: airbyte
    ports:
      - "5432:5432"
    volumes:
      - airbyte-db-data:/var/lib/postgresql/data

  redis:
    image: redis:6
    ports:
      - "6379:6379"

  airbyte-server:
    image: airbyte/airbyte-server:0.47.21-alpha
    depends_on:
      - airbyte-db
      - redis
    environment:
      - AIRBYTE_DATABASE_USER=postgres
      - AIRBYTE_DATABASE_PASSWORD=airbyte
      - AIRBYTE_DATABASE_DB=airbyte
      - AIRBYTE_DATABASE_HOST=airbyte-db
      - AIRBYTE_REDIS_HOST=redis
      - AIRBYTE_WORKSPACE_ROOT=/tmp/airbyte_workspace
    volumes:
      - ./airbyte_workspace:/tmp/airbyte_workspace
    ports:
      - "8000:8000"

volumes:
  airbyte-db-data:
